// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `file_service_reg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package bottle.distributed.register.reg;

public final class IFileServerCenterPrxHolder
{
    public
    IFileServerCenterPrxHolder()
    {
    }

    public
    IFileServerCenterPrxHolder(IFileServerCenterPrx value)
    {
        this.value = value;
    }

    public IFileServerCenterPrx value;
}
