// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `file_service_reg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package bottle.distributed.register.reg;

public final class IFileServerCenterHolder extends Ice.ObjectHolderBase<IFileServerCenter>
{
    public
    IFileServerCenterHolder()
    {
    }

    public
    IFileServerCenterHolder(IFileServerCenter value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof IFileServerCenter)
        {
            value = (IFileServerCenter)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _IFileServerCenterDisp.ice_staticId();
    }
}
