// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `file_service_reg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package bottle.distributed.register.reg;

/**
 * 提供 动态注册于删除文件服务器信息接口
 * 提供客户端 获取有效文件服务器信息
 **/
public interface IFileServerCenter extends Ice.Object,
                                           _IFileServerCenterOperations, _IFileServerCenterOperationsNC
{
    public static final String ice_staticId = "::reg::IFileServerCenter";

    public static final long serialVersionUID = 181765836L;
}
