// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `driver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hsf.framework.api.driver;

/**
 * 根据 用户ID 查询其 所属全部企业列表信息
 * userid 用户ID
 **/

public abstract class Callback_DriverService_driverQueryCompList
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<com.hsf.framework.api.driver.DriverCompInfo[]>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        DriverServicePrxHelper.__driverQueryCompList_completed(this, __result);
    }
}
