// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `driver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hsf.framework.api.driver;

/**
 * 根据 用户码 ,企业码 ,指定的订单状态 , 获取订单列表 - 简单信息
 * userid 用户码
 * enterpriseid 企业码
 * state 查询的状态值
 * return 订单对象数组 (包含订单简略信息)
 **/

public abstract class Callback_DriverService_driverQueryOrderList
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<com.hsf.framework.api.driver.OrderInfo[]>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        DriverServicePrxHelper.__driverQueryOrderList_completed(this, __result);
    }
}
