// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `driver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hsf.framework.api.driver;

/**
 * 对订单进行状态修改操作
 * userid 用户码 - 在取货时需要与用户码绑定
 * enterpriseid 企业号
 * info 订单号
 * state 需要修改的状态
 * 操作成功返回true
 **/

public abstract class Callback_DriverService_driverOrderStateOp
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackBool
{
    public final void __completed(Ice.AsyncResult __result)
    {
        DriverServicePrxHelper.__driverOrderStateOp_completed(this, __result);
    }
}
