// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `driver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hsf.framework.api.driver;

/**
 * 司机登录
 * phone: 司机登录电话号码
 * pw:司机密码(MD5加密)
 * 请判断角色码
 **/

public abstract class Callback_DriverService_driverLogin
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<com.hsf.framework.api.driver.DriverBase>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        DriverServicePrxHelper.__driverLogin_completed(this, __result);
    }
}
