// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `driver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hsf.framework.api.driver;

/**
 * 用户基本信息数据模型
 **/
public class DriverBase implements java.lang.Cloneable, java.io.Serializable
{
    public int oid;

    public long uphone;

    public String urealname;

    public int code;

    public String msg;

    public DriverBase()
    {
        urealname = "";
        msg = "";
    }

    public DriverBase(int oid, long uphone, String urealname, int code, String msg)
    {
        this.oid = oid;
        this.uphone = uphone;
        this.urealname = urealname;
        this.code = code;
        this.msg = msg;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DriverBase _r = null;
        if(rhs instanceof DriverBase)
        {
            _r = (DriverBase)rhs;
        }

        if(_r != null)
        {
            if(oid != _r.oid)
            {
                return false;
            }
            if(uphone != _r.uphone)
            {
                return false;
            }
            if(urealname != _r.urealname)
            {
                if(urealname == null || _r.urealname == null || !urealname.equals(_r.urealname))
                {
                    return false;
                }
            }
            if(code != _r.code)
            {
                return false;
            }
            if(msg != _r.msg)
            {
                if(msg == null || _r.msg == null || !msg.equals(_r.msg))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::driver::DriverBase");
        __h = IceInternal.HashUtil.hashAdd(__h, oid);
        __h = IceInternal.HashUtil.hashAdd(__h, uphone);
        __h = IceInternal.HashUtil.hashAdd(__h, urealname);
        __h = IceInternal.HashUtil.hashAdd(__h, code);
        __h = IceInternal.HashUtil.hashAdd(__h, msg);
        return __h;
    }

    public DriverBase
    clone()
    {
        DriverBase c = null;
        try
        {
            c = (DriverBase)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(oid);
        __os.writeLong(uphone);
        __os.writeString(urealname);
        __os.writeInt(code);
        __os.writeString(msg);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        oid = __is.readInt();
        uphone = __is.readLong();
        urealname = __is.readString();
        code = __is.readInt();
        msg = __is.readString();
    }

    static public void
    __write(IceInternal.BasicStream __os, DriverBase __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public DriverBase
    __read(IceInternal.BasicStream __is, DriverBase __v)
    {
        if(__v == null)
        {
             __v = new DriverBase();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final DriverBase __nullMarshalValue = new DriverBase();

    public static final long serialVersionUID = -1249692562L;
}
