// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `driver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hsf.framework.api.driver;

/**
 * 司机app服务
 **/
public interface DriverService extends Ice.Object,
                                       _DriverServiceOperations, _DriverServiceOperationsNC
{
    public static final String ice_staticId = "::driver::DriverService";

    public static final long serialVersionUID = -210141824L;
}
