// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `driver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hsf.framework.api.driver;

/**
 * 订单数据简略模型
 **/
public class OrderBrief implements java.lang.Cloneable, java.io.Serializable
{
    public String adds;

    public String time;

    public String cargo;

    public String pay;

    public OrderBrief()
    {
        adds = "";
        time = "";
        cargo = "";
        pay = "";
    }

    public OrderBrief(String adds, String time, String cargo, String pay)
    {
        this.adds = adds;
        this.time = time;
        this.cargo = cargo;
        this.pay = pay;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        OrderBrief _r = null;
        if(rhs instanceof OrderBrief)
        {
            _r = (OrderBrief)rhs;
        }

        if(_r != null)
        {
            if(adds != _r.adds)
            {
                if(adds == null || _r.adds == null || !adds.equals(_r.adds))
                {
                    return false;
                }
            }
            if(time != _r.time)
            {
                if(time == null || _r.time == null || !time.equals(_r.time))
                {
                    return false;
                }
            }
            if(cargo != _r.cargo)
            {
                if(cargo == null || _r.cargo == null || !cargo.equals(_r.cargo))
                {
                    return false;
                }
            }
            if(pay != _r.pay)
            {
                if(pay == null || _r.pay == null || !pay.equals(_r.pay))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::driver::OrderBrief");
        __h = IceInternal.HashUtil.hashAdd(__h, adds);
        __h = IceInternal.HashUtil.hashAdd(__h, time);
        __h = IceInternal.HashUtil.hashAdd(__h, cargo);
        __h = IceInternal.HashUtil.hashAdd(__h, pay);
        return __h;
    }

    public OrderBrief
    clone()
    {
        OrderBrief c = null;
        try
        {
            c = (OrderBrief)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(adds);
        __os.writeString(time);
        __os.writeString(cargo);
        __os.writeString(pay);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        adds = __is.readString();
        time = __is.readString();
        cargo = __is.readString();
        pay = __is.readString();
    }

    static public void
    __write(IceInternal.BasicStream __os, OrderBrief __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public OrderBrief
    __read(IceInternal.BasicStream __is, OrderBrief __v)
    {
        if(__v == null)
        {
             __v = new OrderBrief();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final OrderBrief __nullMarshalValue = new OrderBrief();

    public static final long serialVersionUID = -372803562L;
}
