// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `driver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hsf.framework.api.driver;

/**
 * 订单信息
 **/
public class OrderInfo implements java.lang.Cloneable, java.io.Serializable
{
    public long orderNo;

    public int state;

    public OrderBrief brief;

    public OrderComplex complex;

    public OrderInfo()
    {
        brief = new OrderBrief();
        complex = new OrderComplex();
    }

    public OrderInfo(long orderNo, int state, OrderBrief brief, OrderComplex complex)
    {
        this.orderNo = orderNo;
        this.state = state;
        this.brief = brief;
        this.complex = complex;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        OrderInfo _r = null;
        if(rhs instanceof OrderInfo)
        {
            _r = (OrderInfo)rhs;
        }

        if(_r != null)
        {
            if(orderNo != _r.orderNo)
            {
                return false;
            }
            if(state != _r.state)
            {
                return false;
            }
            if(brief != _r.brief)
            {
                if(brief == null || _r.brief == null || !brief.equals(_r.brief))
                {
                    return false;
                }
            }
            if(complex != _r.complex)
            {
                if(complex == null || _r.complex == null || !complex.equals(_r.complex))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::driver::OrderInfo");
        __h = IceInternal.HashUtil.hashAdd(__h, orderNo);
        __h = IceInternal.HashUtil.hashAdd(__h, state);
        __h = IceInternal.HashUtil.hashAdd(__h, brief);
        __h = IceInternal.HashUtil.hashAdd(__h, complex);
        return __h;
    }

    public OrderInfo
    clone()
    {
        OrderInfo c = null;
        try
        {
            c = (OrderInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(orderNo);
        __os.writeInt(state);
        OrderBrief.__write(__os, brief);
        OrderComplex.__write(__os, complex);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        orderNo = __is.readLong();
        state = __is.readInt();
        brief = OrderBrief.__read(__is, brief);
        complex = OrderComplex.__read(__is, complex);
    }

    static public void
    __write(IceInternal.BasicStream __os, OrderInfo __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public OrderInfo
    __read(IceInternal.BasicStream __is, OrderInfo __v)
    {
        if(__v == null)
        {
             __v = new OrderInfo();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final OrderInfo __nullMarshalValue = new OrderInfo();

    public static final long serialVersionUID = 719523607L;
}
