// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `driver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hsf.framework.api.driver;

/**
 * 已取货 可以获取待运输列表 , 成功签收后改变状态为 已签收,途中货物卸货停止轨迹,当被其他司机扫码取货后,变为已取货状态
 **/
public interface sCLAIM
{
    int value = 3;
}
